config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'projects#index'

  devise_for :users

  resources :developers, except: :show

  resources :projects do
    member do
      get :manage_developers
      get :add_developer
    end

    resources :sprints, only: %i[index create]
  end

  resource :user_projects, only: [:destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects
  has_many :sprints, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :name, length: 4..20, allow_blank: true
  scope :id_ordered_desc, -> { order(id: :desc) }

  def project_developer_ids(current_user)
    user_projects.where.not(user_id: current_user.id).pluck(:user_id)
  end

  def self.with_sprints(id)
    preload(:sprints).find_by(id: id)
  end
end

app/models/sprint.rb
# frozen_string_literal: true

class Sprint < ApplicationRecord
  belongs_to :project

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :user_projects, dependent: :destroy
  has_many :projects, through: :user_projects
  has_many :subordinates, class_name: 'User', foreign_key: :lead_id, dependent: :destroy, inverse_of: :lead
  belongs_to :lead, class_name: 'User', optional: true

  validates :email, presence: true, uniqueness: true
  validates :user_name, presence: true

  before_validation :nullify_password_for_developers

  enum role: { lead: 0, developer: 1 }

  scope :id_ordered_desc, -> { order(id: :desc) }

  attr_accessor :skip_password_validation  # virtual attribute to skip password validation while saving

  def nullify_password_for_developers
    self.skip_password_validation = true if developer?
  end

  protected

  def password_required?
    return false if skip_password_validation

    super
  end
end

app/models/user_project.rb
# frozen_string_literal: true

class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do
    flash[:danger] = 'You do not have permission to access this page.'
    redirect_to root_url
  end

  rescue_from ActiveRecord::RecordNotFound do
    flash[:notice] = 'Something went Wrong...'
    redirect_to root_url
  end

  rescue_from ActiveRecord::RecordNotDestroyed do
    flash[:notice] = 'Something went Wrong...'
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation user_name])
  end
end

app/controllers/developers_controller.rb
# frozen_string_literal: true

class DevelopersController < ApplicationController
  before_action :set_developer, except: %i[index create new]

  def index
    @developers = current_user.subordinates.id_ordered_desc
  end

  def new
    @developer = User.new
    authorize @developer
  end

  def edit
  end

  def create
    @developer = User.new(user_params)
    authorize @developer
    if @developer.save
      current_user.subordinates << @developer

      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @developer.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @developer.destroy
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream
      end
    else
      redirect_to projects_path, flash: { failure: 'Unable to delete user' }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :user_name, :role)
  end

  def set_developer
    @developer = User.find_by(id: params[:id])
    authorize @developer
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  # before_action :authorization
  before_action :set_project, except: %i[index create new]

  def index
    @projects = current_user.projects.id_ordered_desc
    authorize @projects
  end

  def show
    @developers = User.where(id: @project.project_developer_ids(current_user))
    @sprints = @project.sprints.count
  end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = current_user.projects.create(project_params)
    if @project.valid?
      respond_to do |format|
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @project.update(project_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @project.present?
      redirect_to projects_path, flash: { failure: 'Project cant be deleted' } unless @project.destroy

      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Project was successfully destroyed.' }
        format.turbo_stream
      end
    else
      redirect_to projects_path, flash: { failure: 'Project does not exists.' }
    end
  end

  def manage_developers
    developer_ids = current_user.subordinates.where.not(id: @project.project_developer_ids(current_user))
    @developers = User.where(id: developer_ids)
  end

  def add_developer
    user = fetch_developer
    @project.user_projects.create(user: user)
    redirect_back fallback_location: manage_developers_project_path(@project)
  end

  private

  def project_params
    params.require(:project).permit(:name)
  end

  def fetch_developer
    User.find_by(id: params[:developer_id])
  end

  def set_project
    @project = Project.preload(:user_projects).find_by(id: params[:id])
    return redirect_to root_path if @project.nil?

    authorize @project
  end
end

app/controllers/sprints_controller.rb
# frozen_string_literal: true

class SprintsController < ApplicationController
  before_action :set_project

  def index
    @schedule = manage_sprint_schedule(schedule_service_params)
  end

  def create
    manage_sprint_schedule(schedule_service_params)

    redirect_back fallback_location: project_path(@project)
  end

  def manage_sprint_schedule(service_params)
    ShuffleSprintDevelopers.new(service_params).call
  end

  private

  def schedule_service_params
    {
      project_id: @project.id,
      sprints: params[:sprints],
      current_user_id: current_user.id,
      generate_schedule: params[:sprints].blank?
    }
  end

  def set_project
    @project = current_user.projects
                           .where(id: params[:project_id])
                           .with_sprints(params[:project_id])

    return redirect_to root_path if @project.nil?

    authorize @project
  end

  def authorization
    authorize Sprint
  end
end

app/controllers/user_projects_controller.rb
# frozen_string_literal: true

class UserProjectsController < ApplicationController
  # before_action :authorization
  before_action :set_project_and_user

  def destroy
    if @developer.destroy
      respond_to do |format|
        format.html { redirect_to project_path(params[:project_id]), notice: 'Project was successfully destroyed.' }
        format.turbo_stream
      end
    end
  end

  private

  def set_project_and_user
    @project = Project.find_by(id: params[:project_id])
    @developer = @project.user_projects.find_by(user_id: params[:developer_id])
    authorize @developer
  end

  def authorization
    authorize UserProject
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/developers/_form.html.erb
<%= form_with model: developer, url: url, method: method do |form| %>
  <% if developer.errors.any? %>
    <% developer.errors.full_messages.each do |message|%>
      <h3><%= message %> </h3>
    <%end%>
  <%end%>

  <%= form.hidden_field :role, value: :developer %>

  <div class='mb-6'>
    <%= form.label :email, class:'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <%= form.text_field :email, class: 'mr-2 input-field', required: true, autofocus: true %>
  </div>
  <div class='mb-6'>
    <%= form.label :user_name, class:'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <div class='flex flex-row justify-between'>
      <%= form.text_field :user_name, class: 'mr-2 input-field', required: true %>
      <%= link_to developers_path, class: 'btn-danger' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
      <% end %>
      <%= button_tag class: 'btn-primary' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/developers/create.turbo_stream.erb
<%= turbo_stream.prepend 'developers', render(DevRow.new(developer: @developer)) %>
<%= turbo_stream.update User.new, '' %>

app/views/developers/destroy.turbo_stream.erb
<%= turbo_stream.remove "dev-row-#{@developer.id}" %>

app/views/developers/edit.html.erb
<%= turbo_frame_tag "dev-row-#{@developer.id}" do %>
  <%= render 'form', developer: @developer, method: :put, url: developer_path %>
<% end %>

app/views/developers/index.html.erb
<div class='container'>
  <div class='flex flex-row justify-between mb-10'>
    <h1 class='text-3xl font-bold tracking-tight text-gray-900 dark:text-white'> Developers </h1>
    <%= link_to new_developer_path, class: 'btn-success', data: { turbo_frame: dom_id(User.new) } do %>
      <div class='flex flex-row items-center pr-2'>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
        <p>Create Developer</p>
      </div>
    <% end %>
  </div>
  <%= turbo_frame_tag User.new %>
  <%= turbo_frame_tag 'developers', class: 'flex flex-col justify-start' do %>
    <%= render(DevRow.with_collection(@developers)) %>
  <% end %>
</div>

app/views/developers/new.html.erb
<%= turbo_frame_tag @developer do %>
  <%= render 'form', developer: @developer, method: :post, url: developers_path %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="bg-white px-2 sm:px-4 py-2.5 dark:bg-gray-900 w-full border-b border-gray-200 dark:border-gray-600">
  <div class="container flex flex-wrap items-center justify-between mx-auto">
    <a href="/" class="flex items-center">
        <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Fair Pair</span>
    </a>
    <div class="flex md:order-2">
        <% if user_signed_in?%>
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn-danger' %>
        <% end %>
    </div>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
    <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      <li>
        <a href="<%= root_path %>" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"" aria-current="page">Projects</a>
      </li>
      <li>
        <a href="<%= developers_path %>" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Developers</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fairpair</title>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'tailwind', 'inter-font', 'data-turbo-track': 'reload' %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='dark:bg-gray-800'>
    <%= render 'layouts/navbar' %>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <main class='container max-auto mt-5 px-5 flex'>
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: project do |form| %>
  <% if project.errors.any? %>
    <% project.errors.full_messages.each do |message|%>
      <h3><%= message %> </h3>
    <%end%>
  <%end%>
  <div class='mb-6'>
    <%= form.label :name, class:'block mb-2 text-sm font-medium text-gray-900 dark:text-white' %>
    <div class='flex flex-row justify-between'>
      <%= form.text_field :name, class: 'mr-2 input-field', required: true, autofocus: true, maxlength: 20 %>
      <%= link_to root_path, class: 'btn-danger' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
      <% end %>
      <%= button_tag class: 'btn-primary' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<%= turbo_frame_tag project do %>
  <div class='flex flex-row justify-between bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600'>
    <div class='py-4 px-6 text-left font-medium text-gray-900 whitespace-nowrap dark:text-white'>
      <p class='text-lg'><%= project.name %></p>
    </div>
    <div class='flex flex-row justify-end py-4 px-6'>
      <%= link_to project_path(project), class: 'btn-primary' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path></svg>
      <% end %>
      <%= link_to edit_project_path(project), class: 'btn-success' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
      <% end %>
      <%= button_to project_path(project), method: :delete, class: 'btn-danger' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/projects/create.turbo_stream.erb
<%= turbo_stream.prepend 'projects', @project %>
<%= turbo_stream.update Project.new, '' %>

app/views/projects/destroy.turbo_stream.erb
<%= turbo_stream.remove @project %>

app/views/projects/edit.html.erb
<%= turbo_frame_tag @project do %>
  <%= render 'form', project: @project %>
<% end %>

app/views/projects/index.html.erb
<div class='container'>
  <div class='flex flex-row justify-between mb-10'>
    <h1 class='text-3xl font-bold tracking-tight text-gray-900 dark:text-white'> Projects </h1>
    <%= link_to new_project_path, class: 'btn-success', data: { turbo_frame: dom_id(Project.new) } do %>
      <div class='flex flex-row items-center pr-2'>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
        <p>Create Project</p>
      </div>
    <% end %>
  </div>
  <%= turbo_frame_tag Project.new %>
  <%= turbo_frame_tag 'projects', class: 'flex flex-col justify-start' do %>
    <%= render @projects %>
  <% end %>
</div>

app/views/projects/manage_developers.html.erb
<div class='container flex flex-col'>
  <div class='flex items-center mb-3'>
    <%= link_to project_path(@project), class: 'text-gray-900 dark:text-white' do %>
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
    <% end %>
    <h2 class='text-xl font-bold tracking-tight text-gray-900 dark:text-white'>Developer Team:</h2>
  </div>
  <div class='overflow-x-auto relative shadow-md sm:rounded-lg mb-2'>
    <table class='w-full text-sm text-left text-gray-500 dark:text-gray-400'>
      <thead class='text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400'>
        <tr>
          <th scope='col' class='py-3 px-6'>
            Developer name
          </th>
          <th scope='col' class='py-3 px-6'>
            <span class='sr-only'>Edit</span>
          </th>
          </tr>
      </thead>
      <tbody>
        <%= render(ManageDeveloper.with_collection(@developers, project: @project)) %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<%= turbo_frame_tag @project do %>
  <%= render 'form', project: @project %>
<% end %>

app/views/projects/show.html.erb
<div class='container'>
  <div class='flex flex-row justify-between mb-10'>
    <div class='flex items-center'>
      <%= link_to root_path, class: 'text-gray-900 dark:text-white' do %>
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
      <% end %>
      <h2 class='text-3xl font-bold tracking-tight text-gray-900 dark:text-white'><%= @project.name %></h2>
    </div>
    <div data-controller='modal' class='flex flex-row justify-between'>
      <button data-action= 'modal#open_sprint', class='btn-success' >Manage Sprints</button>
      <%= render(SprintModal.new(project: @project, sprints: @sprints)) %>
      <%= link_to 'Add Devs', manage_developers_project_path(@project), class: 'btn-success' %>
    </div>
  </div>
  <% if @developers.any? %>
    <div class='ml-5'>
      <h3 class='text-xl font-bold tracking-tight text-gray-900 dark:text-white'>Projet Team:</h3>
      <%= turbo_frame_tag 'project_developers', class: 'flex flex-col justify-start mb-3' do %>
        <%= render(ProjectDeveloper.with_collection(@developers, project: @project)) %>
      <% end %>
    </div>
  <% else %>
    <div class='text-center mt-10 mb-5'>
      <h3 class='text-xl font-bold tracking-tight text-gray-900 dark:text-white'>Add Devs to the project to see the list here!</h3>
    </div>
  <% end %>
  <div class='flex items-center justify-center'>
    <% if @project.project_developer_ids(current_user).present? && @project.sprints.exists?%>
      <%=link_to 'See Schedule', project_sprints_path(@project), class: 'btn-primary' %>
    <% end %>
  </div>
</div>

app/views/sprints/index.html.erb
<div class='container flex flex-col'>
  <div class='flex items-center'>
    <%= link_to project_path(@project), class: 'text-gray-900 dark:text-white' do %>
      <svg class="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>
    <% end %>
    <h1 class="text-3xl font-bold tracking-tight text-gray-900 dark:text-white">Sprints schedule</h1>
  </div>
  <div class="overflow-x-auto relative mt-5">
    <%= render(SprintTable.with_collection(@project.sprints, schedule: @schedule)) %>
  </div>
</div>

app/views/user_projects/destroy.turbo_stream.erb
<%= turbo_stream.remove "developer-#{params[:developer_id]}" %>